### ISSUE TITLE
Kanban Board : Setup

### ISSUE THREAD

**Issue by EmekaEmmanuel** [EmekaEmmanuel/capstone2#21]
https://github.com/EmekaEmmanuel/capstone2/projects/1

There are three (3) people in my team.

@zewdu444  
@jugosack 
@EmekaEmmanuel

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Good implementations ✔️ 

## Required Changes ♻️
- [REQUIRED] Good job so far! Kindly fix your link of your `GitHub Project` you provided on your issue's description to [correct one](https://github.com/EmekaEmmanuel/capstone2/projects/1), please 🙏🏼  

#
![image](https://user-images.githubusercontent.com/63915024/216992435-8bbfe767-3a0a-45b1-9b2f-ed2ffccb35b3.png)
#
 
- [REQUIRED] Good job so far! The `Group` tasks should be assigned all team members, please add other teammebers to all `Group` tasks 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/216999501-92f153e2-465c-4e51-9651-384c734a4a35.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Munsa1** [comment]
Hi @EmekaEmmanuel @jugosack @zewdu444, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
N/A

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
